export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  STRIPE_ERROR: 'STRIPE_ERROR',
  NO_SUBSCRIPTION: 'NO_SUBSCRIPTION',
  EMAIL_PROVIDER_NOT_CONFIGURED: 'EMAIL_PROVIDER_NOT_CONFIGURED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INTERNAL: 'INTERNAL',
  ACCOUNT_DELETION_PENDING: 'ACCOUNT_DELETION_PENDING',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  STORAGE_NOT_CONFIGURED: 'STORAGE_NOT_CONFIGURED',
  // Forward-declared for template consumers' own credit-gated server
  // functions (see docs/warpkit/features/credits.md). Currently unused in-repo, not
  // dead code , deductCredit()'s only caller is a raw H3 route handler, not a
  // createServerFn, so it never returns a Result<T> itself.
  NO_CREDITS: 'NO_CREDITS',
  EMAIL_DISPOSABLE: 'EMAIL_DISPOSABLE',
  EMAIL_DOMAIN_INVALID: 'EMAIL_DOMAIN_INVALID',
  CANCEL_FAILED: 'CANCEL_FAILED',
  RETRY_FAILED: 'RETRY_FAILED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  VERIFY_FAILED: 'VERIFY_FAILED'
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

declare module '@bitclaw/result' {
  interface RegisteredErrCodes extends Record<ErrorCode, true> {}
}

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  RATE_LIMITED: 429,
  STRIPE_ERROR: 502,
  NO_SUBSCRIPTION: 402,
  EMAIL_PROVIDER_NOT_CONFIGURED: 500,
  EMAIL_SEND_FAILED: 500,
  INTERNAL: 500,
  ACCOUNT_DELETION_PENDING: 409,
  PLAN_LIMIT_EXCEEDED: 403,
  STORAGE_NOT_CONFIGURED: 503,
  NO_CREDITS: 402,
  EMAIL_DISPOSABLE: 422,
  EMAIL_DOMAIN_INVALID: 422,
  CANCEL_FAILED: 409,
  RETRY_FAILED: 409,
  ACCOUNT_BANNED: 403,
  VERIFY_FAILED: 502
};
