// Production server entry point. Requires `bun run build` first.
//
// Serves prerendered HTML and static assets from dist/client/ before
// delegating to the SSR handler. Add new static HTML pages to
// STATIC_HTML_PATHS (src/lib/prerendered-paths.ts), read by both this file
// and vite.config.ts's prerender filter - see
// docs/warpkit/features/static-prerendering.md for the full picture.
//
// Also the real home for server-boot side effects (job workers, Sentry init,
// startup reconciliation) that were previously written as server/plugins/
// Nitro plugins. Those never actually ran: Nitro's plugin auto-load only
// fires when Nitro's own Vite plugin is registered with a scanDirs pointing
// at server/, which this project never did (see docs/warpkit/features/jobs.md and
// CLAUDE.md's "Background Jobs" section). This file is the one place
// guaranteed to run in production and never inspected by Vite's client
// bundler, so it's also where src/start.ts's reconciliation logic had to
// move to, for the same reason it couldn't live in src/start.ts directly
// (see the comment there).
import fs from 'node:fs';
import path from 'node:path';
import { allPosts } from 'content-collections';
import { createLogger } from '@/lib/logger';
import { STATIC_HTML_PATHS } from '@/lib/prerendered-paths';
import {
  AUTH_PAGE_CACHE_CONTROL,
  LANDING_PAGE_CACHE_CONTROL
} from '@/lib/ssr-cache-headers';
import { applySecurityHeaders } from '@/server/csp';
import {
  buildAssetResponse,
  buildStaticAssetRoutes,
  loadAssetForPreload,
  readAssetPreloadConfig
} from './static-assets';

const log = createLogger({ module: 'startup' });

const distClient = path.resolve(import.meta.dirname, '..', 'dist', 'client');
const PORT = Number(process.env.PORT ?? 3000);

// Maps URL pathnames to prerendered HTML files generated by `bun run build`.
// Static (non-blog) entries are derived from STATIC_HTML_PATHS
// (src/lib/prerendered-paths.ts), the same list vite.config.ts's prerender
// filter reads - a path in one but not the other used to fail silently
// (falls through to the SSR handler below instead of a build error), which
// is exactly what broke robots.txt/sitemap.xml before both were pulled from
// this one shared list. Blog posts are derived from `allPosts` instead,
// since the filter finds them via crawlLinks, not a static list either -
// neither list can drift from what it's sourced from.
const prerenderedIndexHtml = (urlPath: string): string =>
  path.join(distClient, urlPath, 'index.html');

// Paths that must never be edge/browser-cached even though they're
// prerendered - see AUTH_PAGE_CACHE_CONTROL's comment in ssr-cache-headers.ts.
// Checked below instead of hardcoding 'no-store' here so this and _auth.tsx's
// SSR path can't drift apart again (that drift is what caused warpkit.dev's
// 2026-08-15 incident: _auth.tsx set a short-cache header, but this fast path
// served a cookie-less /login request straight from disk with the long-lived
// landing page header, bypassing _auth.tsx entirely).
const AUTH_PRERENDERED_PATHS = new Set(['/login', '/signup']);

const PRERENDERED: Record<string, string> = {
  ...Object.fromEntries(
    STATIC_HTML_PATHS.map(urlPath => [
      urlPath,
      urlPath === '/'
        ? path.join(distClient, 'index.html')
        : prerenderedIndexHtml(urlPath.slice(1))
    ])
  ),
  ...Object.fromEntries(
    allPosts.map(post => [
      `/blog/${post.slug}`,
      prerenderedIndexHtml(`blog/${post.slug}`)
    ])
  )
};

// Must match cookiePrefix in src/server/auth.ts and config.ts.
// Imported from config.ts so it stays in sync when appName changes.
// ssr: 'data-only' on _app dehydrates the / route's beforeLoad result (undefined)
// into the prerendered HTML, causing TanStack Router to skip re-running beforeLoad
// on hydration. Authenticated users bypass ALL prerendered paths below, not just
// / - only / actually needs this (its beforeLoad redirects logged-in users to
// /dashboard), but the other marketing/blog pages have no session-dependent
// content either way, so gating them the same way is free consistency, not a
// separate mechanism to reason about.
const { SESSION_COOKIE_NAME } = await import('../config');

const MIME: Record<string, string> = {
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.json': 'application/json',
  '.webmanifest': 'application/manifest+json',
  '.txt': 'text/plain',
  '.xml': 'application/xml'
};

// robots.txt/sitemap.xml are prerendered server routes (see
// vite.config.ts's `pages` array), so they land in the generic static-asset
// branch below like any other non-hashed file - which defaults to
// max-age=0, must-revalidate. Override to preserve the longer TTLs the
// routes themselves used to set at request time (src/routes/robots[.]txt.ts,
// sitemap[.]xml.ts).
const SEO_CACHE_CONTROL: Record<string, string> = {
  '/robots.txt': 'public, max-age=86400',
  '/sitemap.xml': 'public, max-age=3600'
};

const { default: ssr } = await import('../dist/server/server.js');

const sentryDsn = process.env.VITE_SENTRY_DSN;
if (sentryDsn) {
  const { init } = await import('@sentry/tanstackstart-react');
  init({
    dsn: sentryDsn,
    environment: process.env.NODE_ENV ?? 'development',
    tracesSampleRate: 0.2,
    sendDefaultPii: false
  });
}

const { startWorkers, stopWorkers } = await import('@/features/jobs/workers');
startWorkers();

// Fire-and-forget safety-net reconcilers, not a boot gate , webhooks are the
// fast path, this just catches whatever they missed. Don't await these or
// server startup ends up blocked on a Stripe API call for no benefit.
// Always logs on completion (not gated on processed/failed > 0) - a silent
// 0/0 result and a reconciler that never actually ran are otherwise
// indistinguishable in the logs. tests/boot-smoke.ts asserts on this line to
// prove the fire-and-forget import chain actually executes, not just that
// job workers started.
import('@/lib/operations/account-deletion.server')
  .then(async ({ reconcilePendingDeletions }) => {
    try {
      const { processed, failed } = await reconcilePendingDeletions();
      log.info({ processed, failed }, 'account deletion reconcile complete');
    } catch (error) {
      log.error({ error }, 'account deletion reconcile failed');
    }
  })
  .catch(error => {
    log.error({ error }, 'account deletion reconcile module failed to load');
  });

import('@/lib/operations/billing-reconciliation.server')
  .then(async ({ reconcileBillingSubscriptions }) => {
    try {
      const { synced, errors } = await reconcileBillingSubscriptions();
      log.info({ synced, errors }, 'billing reconcile complete');
    } catch (error) {
      log.error({ error }, 'billing reconcile failed');
    }
  })
  .catch(error => {
    log.error({ error }, 'billing reconcile module failed to load');
  });

const shutdown = async (): Promise<void> => {
  await stopWorkers();
  const { closeAllUserDbs } = await import('@/lib/db/user-db');
  closeAllUserDbs();
  const { closeSharedDb } = await import('@/lib/db');
  closeSharedDb();
  const { closeJobQueue } = await import('@/features/jobs/queue.server');
  closeJobQueue();
  process.exit(0);
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

// Re-applies security headers to any Response and clones it through - same
// pattern for both response categories below (fast-path static/prerendered
// content, and real SSR), just with a different isProduction value per
// category (see the two functions below for why they differ).
const rewriteWithSecurityHeaders = (
  response: Response,
  isProduction: boolean
): Response => {
  const headers = new Headers(response.headers);
  applySecurityHeaders(headers, isProduction);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
};

// Fast-path responses (prerendered HTML with no session cookie, static
// assets) only exist once a real build has run, so there's nothing to relax
// for local dev - always isProduction=true. Wraps a plain handler so 200s,
// 304s, and anything else the handler returns all get headers the same way.
const withFastPathSecurityHeaders =
  (handler: (req: Request) => Response | Promise<Response>) =>
  async (req: Request): Promise<Response> =>
    rewriteWithSecurityHeaders(await handler(req), true);

// Not just a passthrough: a thrown redirect() and the router's not-found
// handling both produce a Response that never reaches securityMiddleware's
// setResponseHeader calls in src/start.ts (that middleware only decorates
// the response TanStack Start itself builds for a resolved route, not a
// Response thrown mid-loader) - confirmed via manual curl against a
// redirecting route and a nonexistent path, both missing HSTS/CSP/
// X-Frame-Options while a normal 200 SSR page carried them correctly.
// Re-applying here guarantees every response leaving this process carries
// the headers, regardless of which internal path produced it. Used both by
// the wildcard SSR fallback below and by a prerendered route's handler when
// a session cookie is present (same delegation, same header policy either
// way - unlike the fast paths, this one does vary with NODE_ENV so relaxed
// CSP/no-HSTS still work for `bun run dev`-adjacent local testing).
const deliverSsrResponse = async (request: Request): Promise<Response> =>
  rewriteWithSecurityHeaders(
    await ssr.fetch(request),
    process.env.NODE_ENV === 'production'
  );

const assetPreloadConfig = readAssetPreloadConfig();

// One route per prerendered HTML path - skip anything not actually built
// (fs.existsSync gate matches the old code's behavior: a missing file means
// this path gets no fast path at all, not even the cookie check, straight
// to SSR for every request). GET-scoped so a POST to a prerendered path
// still reaches SSR the same as before, not the static file.
const buildPrerenderedRoutes = async (): Promise<
  Record<string, { GET: (req: Request) => Promise<Response> }>
> => {
  const entries = await Promise.all(
    Object.entries(PRERENDERED)
      .filter(([, filepath]) => fs.existsSync(filepath))
      .map(async ([urlPath, filepath]) => {
        const asset = await loadAssetForPreload(
          filepath,
          'text/html; charset=utf-8',
          assetPreloadConfig
        );
        const cacheControl = AUTH_PRERENDERED_PATHS.has(urlPath)
          ? AUTH_PAGE_CACHE_CONTROL
          : LANDING_PAGE_CACHE_CONTROL;

        const handler = async (request: Request): Promise<Response> => {
          const cookie = request.headers.get('cookie') ?? '';
          if (cookie.includes(`${SESSION_COOKIE_NAME}=`)) {
            return deliverSsrResponse(request);
          }
          return withFastPathSecurityHeaders(() =>
            buildAssetResponse(
              asset,
              filepath,
              'text/html; charset=utf-8',
              cacheControl,
              request
            )
          )(request);
        };

        return [urlPath, { GET: handler }] as const;
      })
  );
  return Object.fromEntries(entries);
};

// One route per file under dist/client, including literal on-disk paths
// like /pricing/index.html that PRERENDERED never covered (see
// static-assets.ts's own comment) - the route table itself is now the
// allowlist, so the old path-traversal guard (path.resolve + startsWith
// check) has nothing left to guard against: every servable path was
// discovered from a real directory glob at boot, nothing is resolved from
// a request-supplied pathname at request time anymore.
//
// Both route sets are built concurrently, not sequentially - each involves
// reading/gzipping/hashing every eligible file under dist/client, real work
// that adds meaningful startup latency if serialized.
const [prerenderedRoutes, staticAssetRoutesRaw] = await Promise.all([
  buildPrerenderedRoutes(),
  buildStaticAssetRoutes(
    distClient,
    MIME,
    SEO_CACHE_CONTROL,
    assetPreloadConfig
  )
]);
const staticAssetRoutes = Object.fromEntries(
  Object.entries(staticAssetRoutesRaw).map(([urlPath, { GET }]) => [
    urlPath,
    { GET: withFastPathSecurityHeaders(GET) }
  ])
);

Bun.serve({
  port: PORT,
  reusePort: true,
  // Bun's default idleTimeout is 10s. Any long-lived connection (SSE,
  // streaming response) with a heartbeat/keepalive cadence near that
  // default races Bun's own idle-kill against the heartbeat send and can
  // lose, RSTing the socket mid-stream instead of a clean close (client
  // sees ERR_QUIC_PROTOCOL_ERROR / ERR_HTTP2_PROTOCOL_ERROR). No SSE in
  // this template today, but set generously high preemptively -- runmist
  // (downstream of this template) hit this live in production 2026-08-01
  // once it added SSE dashboards, and the same gap exists here unnoticed
  // until something adds a long-lived connection.
  idleTimeout: 65,
  routes: {
    ...prerenderedRoutes,
    ...staticAssetRoutes,
    // A missing hashed asset (deleted old release, stale cached HTML
    // referencing a chunk that no longer exists) must 404 here rather than
    // fall through to the SSR handler below, which would return the SPA
    // document with a 200. A browser dynamic-import expecting a JS module
    // and getting an HTML document back throws a confusing generic
    // TypeError deep in whatever code destructures the (garbage) module
    // exports, instead of the clean, detectable "Failed to fetch
    // dynamically imported module" error. Matches before this refactor
    // exactly, including that it's the one response in this file with no
    // security headers applied - not touched, only relocated.
    '/assets/*': () => new Response('Not found', { status: 404 }),
    // Plain handler, not GET-scoped - server functions (POST), API routes
    // (PUT/DELETE/etc), and every other method all need to reach real SSR
    // here, not just GET requests to unmatched paths.
    '/*': deliverSsrResponse
  },
  error(error) {
    log.error({ error }, 'uncaught server error');
    const headers = new Headers();
    applySecurityHeaders(headers, process.env.NODE_ENV === 'production');
    return new Response('Internal Server Error', { status: 500, headers });
  }
});

process.stdout.write(`Server running at http://localhost:${PORT}\n`);
