// Production server entry point. Requires `bun run build` first.
//
// Serves prerendered HTML and static assets from dist/client/ before
// delegating to the SSR handler. Add routes to PRERENDERED when you add
// pages to the prerender filter in vite.config.ts , see
// docs/warpkit/features/static-prerendering.md for the full picture.
//
// Also the real home for server-boot side effects (job workers, Sentry init,
// startup reconciliation) that were previously written as server/plugins/
// Nitro plugins. Those never actually ran: Nitro's plugin auto-load only
// fires when Nitro's own Vite plugin is registered with a scanDirs pointing
// at server/, which this project never did (see docs/warpkit/features/jobs.md and
// CLAUDE.md's "Background Jobs" section). This file is the one place
// guaranteed to run in production and never inspected by Vite's client
// bundler, so it's also where src/start.ts's reconciliation logic had to
// move to, for the same reason it couldn't live in src/start.ts directly
// (see the comment there).
import fs from 'node:fs';
import path from 'node:path';
import { allPosts } from 'content-collections';
import { createLogger } from '@/lib/logger';
import {
  AUTH_PAGE_CACHE_CONTROL,
  LANDING_PAGE_CACHE_CONTROL
} from '@/lib/ssr-cache-headers';
import { applySecurityHeaders } from '@/server/csp';

const log = createLogger({ module: 'startup' });

const distClient = path.resolve(import.meta.dirname, '..', 'dist', 'client');
const PORT = Number(process.env.PORT ?? 3000);

// Maps URL pathnames to prerendered HTML files generated by `bun run build`.
// Static (non-blog) entries here must match vite.config.ts's prerender
// filter exactly - a path prerendered there but missing here silently falls
// through to the SSR handler below instead (wrong, but not broken: still
// correct output, just full render cost on every request). Blog posts are
// derived from `allPosts` instead of hand-listed, since the filter itself
// finds them via crawlLinks, not a static list either - one drifts, the
// other can't.
const prerenderedIndexHtml = (urlPath: string): string =>
  path.join(distClient, urlPath, 'index.html');

// Paths that must never be edge/browser-cached even though they're
// prerendered - see AUTH_PAGE_CACHE_CONTROL's comment in ssr-cache-headers.ts.
// Checked below instead of hardcoding 'no-store' here so this and _auth.tsx's
// SSR path can't drift apart again (that drift is what caused warpkit.dev's
// 2026-08-15 incident: _auth.tsx set a short-cache header, but this fast path
// served a cookie-less /login request straight from disk with the long-lived
// landing page header, bypassing _auth.tsx entirely).
const AUTH_PRERENDERED_PATHS = new Set(['/login', '/signup']);

const PRERENDERED: Record<string, string> = {
  '/': path.join(distClient, 'index.html'),
  '/pricing': prerenderedIndexHtml('pricing'),
  '/features': prerenderedIndexHtml('features'),
  '/changelog': prerenderedIndexHtml('changelog'),
  '/contact': prerenderedIndexHtml('contact'),
  '/privacy': prerenderedIndexHtml('privacy'),
  '/tos': prerenderedIndexHtml('tos'),
  '/login': prerenderedIndexHtml('login'),
  '/signup': prerenderedIndexHtml('signup'),
  '/blog': prerenderedIndexHtml('blog'),
  ...Object.fromEntries(
    allPosts.map(post => [
      `/blog/${post.slug}`,
      prerenderedIndexHtml(`blog/${post.slug}`)
    ])
  )
};

// Must match cookiePrefix in src/server/auth.ts and config.ts.
// Imported from config.ts so it stays in sync when appName changes.
// ssr: 'data-only' on _app dehydrates the / route's beforeLoad result (undefined)
// into the prerendered HTML, causing TanStack Router to skip re-running beforeLoad
// on hydration. Authenticated users bypass ALL prerendered paths below, not just
// / - only / actually needs this (its beforeLoad redirects logged-in users to
// /dashboard), but the other marketing/blog pages have no session-dependent
// content either way, so gating them the same way is free consistency, not a
// separate mechanism to reason about.
const { SESSION_COOKIE_NAME } = await import('../config');

const MIME: Record<string, string> = {
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.json': 'application/json',
  '.webmanifest': 'application/manifest+json',
  '.txt': 'text/plain',
  '.xml': 'application/xml'
};

const { default: ssr } = await import('../dist/server/server.js');

const sentryDsn = process.env.VITE_SENTRY_DSN;
if (sentryDsn) {
  const { init } = await import('@sentry/tanstackstart-react');
  init({
    dsn: sentryDsn,
    environment: process.env.NODE_ENV ?? 'development',
    tracesSampleRate: 0.2,
    sendDefaultPii: false
  });
}

const { startWorkers, stopWorkers } = await import('@/features/jobs/workers');
startWorkers();

// Fire-and-forget safety-net reconcilers, not a boot gate , webhooks are the
// fast path, this just catches whatever they missed. Don't await these or
// server startup ends up blocked on a Stripe API call for no benefit.
// Always logs on completion (not gated on processed/failed > 0) - a silent
// 0/0 result and a reconciler that never actually ran are otherwise
// indistinguishable in the logs. tests/boot-smoke.ts asserts on this line to
// prove the fire-and-forget import chain actually executes, not just that
// job workers started.
import('@/lib/operations/account-deletion.server')
  .then(async ({ reconcilePendingDeletions }) => {
    try {
      const { processed, failed } = await reconcilePendingDeletions();
      log.info({ processed, failed }, 'account deletion reconcile complete');
    } catch (error) {
      log.error({ error }, 'account deletion reconcile failed');
    }
  })
  .catch(error => {
    log.error({ error }, 'account deletion reconcile module failed to load');
  });

import('@/lib/operations/billing-reconciliation.server')
  .then(async ({ reconcileBillingSubscriptions }) => {
    try {
      const { synced, errors } = await reconcileBillingSubscriptions();
      log.info({ synced, errors }, 'billing reconcile complete');
    } catch (error) {
      log.error({ error }, 'billing reconcile failed');
    }
  })
  .catch(error => {
    log.error({ error }, 'billing reconcile module failed to load');
  });

const shutdown = async (): Promise<void> => {
  await stopWorkers();
  const { closeAllUserDbs } = await import('@/lib/db/user-db');
  closeAllUserDbs();
  const { closeSharedDb } = await import('@/lib/db');
  closeSharedDb();
  const { closeJobQueue } = await import('@/features/jobs/queue.server');
  closeJobQueue();
  process.exit(0);
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

Bun.serve({
  port: PORT,
  reusePort: true,
  // Bun's default idleTimeout is 10s. Any long-lived connection (SSE,
  // streaming response) with a heartbeat/keepalive cadence near that
  // default races Bun's own idle-kill against the heartbeat send and can
  // lose, RSTing the socket mid-stream instead of a clean close (client
  // sees ERR_QUIC_PROTOCOL_ERROR / ERR_HTTP2_PROTOCOL_ERROR). No SSE in
  // this template today, but set generously high preemptively -- runmist
  // (downstream of this template) hit this live in production 2026-08-01
  // once it added SSE dashboards, and the same gap exists here unnoticed
  // until something adds a long-lived connection.
  idleTimeout: 65,
  async fetch(request) {
    const url = new URL(request.url);

    if (request.method === 'GET') {
      // Prerendered HTML , skip for authenticated users so SSR runs beforeLoad
      const htmlPath = PRERENDERED[url.pathname];
      if (htmlPath && fs.existsSync(htmlPath)) {
        const cookie = request.headers.get('cookie') ?? '';
        if (!cookie.includes(`${SESSION_COOKIE_NAME}=`)) {
          const headers = new Headers({
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': AUTH_PRERENDERED_PATHS.has(url.pathname)
              ? AUTH_PAGE_CACHE_CONTROL
              : LANDING_PAGE_CACHE_CONTROL
          });
          applySecurityHeaders(headers, true);
          return new Response(Bun.file(htmlPath), { headers });
        }
      }

      // Static assets from dist/client , guard against path traversal
      const resolved = path.resolve(distClient, url.pathname.slice(1));
      if (
        resolved.startsWith(distClient + path.sep) &&
        fs.existsSync(resolved)
      ) {
        const stat = fs.statSync(resolved);
        if (stat.isFile()) {
          const ext = path.extname(resolved).toLowerCase();
          const mime = MIME[ext] ?? 'application/octet-stream';
          // /assets/* filenames are content-hashed , safe to cache forever
          const isHashed = url.pathname.startsWith('/assets/');
          const headers = new Headers({
            'Content-Type': mime,
            'Cache-Control': isHashed
              ? 'public, max-age=31536000, immutable'
              : 'public, max-age=0, must-revalidate'
          });
          applySecurityHeaders(headers, true);
          return new Response(Bun.file(resolved), { headers });
        }
      }

      // A missing hashed asset (deleted old release, stale cached HTML
      // referencing a chunk that no longer exists) must 404 here rather than
      // fall through to the SSR handler below, which would return the SPA
      // document with a 200. A browser dynamic-import expecting a JS module
      // and getting an HTML document back throws a confusing generic
      // TypeError deep in whatever code destructures the (garbage) module
      // exports, instead of the clean, detectable
      // "Failed to fetch dynamically imported module" error.
      if (url.pathname.startsWith('/assets/')) {
        return new Response('Not found', { status: 404 });
      }
    }

    // Not just a passthrough: a thrown redirect() and the router's
    // not-found handling both produce a Response that never reaches
    // securityMiddleware's setResponseHeader calls in src/start.ts (that
    // middleware only decorates the response TanStack Start itself builds
    // for a resolved route, not a Response thrown mid-loader) - confirmed
    // via manual curl against a redirecting route and a nonexistent path,
    // both missing HSTS/CSP/X-Frame-Options while a normal 200 SSR page
    // carried them correctly. Re-applying here guarantees every response
    // leaving this process carries the headers, regardless of which
    // internal path produced it.
    const response = await ssr.fetch(request);
    const headers = new Headers(response.headers);
    applySecurityHeaders(headers, process.env.NODE_ENV === 'production');
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers
    });
  }
});

process.stdout.write(`Server running at http://localhost:${PORT}\n`);
