// Ported verbatim from the pre-rewrite site's prisma/seed-cities.ts.
// Climate risk scores and weather averages are hand-curated placeholders
// pending real NOAA-derived scoring - see docs on the weather feature.

export type CitySeed = {
  name: string;
  state: string;
  stateCode: string;
  latitude: number;
  longitude: number;
  population: number;
  wildfireRisk: number;
  floodRisk: number;
  hurricaneRisk: number;
  heatWaveRisk: number;
  droughtRisk: number;
  avgSunshineHours: number;
  avgCloudCover: number;
  avgTempHigh: number;
  avgTempLow: number;
  costOfLivingIndex: number;
  airQualityIndex: number;
};

export const citySeeds: CitySeed[] = [
  // Pacific Northwest - Generally low climate risk, cloudy
  {
    name: 'Seattle',
    state: 'Washington',
    stateCode: 'WA',
    latitude: 47.6062,
    longitude: -122.3321,
    population: 749256,
    wildfireRisk: 25,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 15,
    droughtRisk: 20,
    avgSunshineHours: 4.5,
    avgCloudCover: 65,
    avgTempHigh: 60,
    avgTempLow: 45,
    costOfLivingIndex: 145,
    airQualityIndex: 35
  },
  {
    name: 'Portland',
    state: 'Oregon',
    stateCode: 'OR',
    latitude: 45.5152,
    longitude: -122.6784,
    population: 652503,
    wildfireRisk: 30,
    floodRisk: 25,
    hurricaneRisk: 5,
    heatWaveRisk: 20,
    droughtRisk: 25,
    avgSunshineHours: 4.8,
    avgCloudCover: 60,
    avgTempHigh: 62,
    avgTempLow: 46,
    costOfLivingIndex: 135,
    airQualityIndex: 40
  },
  {
    name: 'Eugene',
    state: 'Oregon',
    stateCode: 'OR',
    latitude: 44.0521,
    longitude: -123.0868,
    population: 176654,
    wildfireRisk: 35,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 18,
    droughtRisk: 22,
    avgSunshineHours: 4.9,
    avgCloudCover: 58,
    avgTempHigh: 61,
    avgTempLow: 42,
    costOfLivingIndex: 110,
    airQualityIndex: 32
  },
  {
    name: 'Spokane',
    state: 'Washington',
    stateCode: 'WA',
    latitude: 47.6588,
    longitude: -117.426,
    population: 229071,
    wildfireRisk: 40,
    floodRisk: 15,
    hurricaneRisk: 5,
    heatWaveRisk: 25,
    droughtRisk: 30,
    avgSunshineHours: 6.2,
    avgCloudCover: 50,
    avgTempHigh: 58,
    avgTempLow: 38,
    costOfLivingIndex: 95,
    airQualityIndex: 38
  },

  // California - High wildfire, varied risks
  {
    name: 'San Francisco',
    state: 'California',
    stateCode: 'CA',
    latitude: 37.7749,
    longitude: -122.4194,
    population: 873965,
    wildfireRisk: 55,
    floodRisk: 25,
    hurricaneRisk: 5,
    heatWaveRisk: 20,
    droughtRisk: 60,
    avgSunshineHours: 7.8,
    avgCloudCover: 35,
    avgTempHigh: 65,
    avgTempLow: 52,
    costOfLivingIndex: 185,
    airQualityIndex: 45
  },
  {
    name: 'Los Angeles',
    state: 'California',
    stateCode: 'CA',
    latitude: 34.0522,
    longitude: -118.2437,
    population: 3898747,
    wildfireRisk: 70,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 55,
    droughtRisk: 70,
    avgSunshineHours: 8.9,
    avgCloudCover: 25,
    avgTempHigh: 75,
    avgTempLow: 57,
    costOfLivingIndex: 165,
    airQualityIndex: 65
  },
  {
    name: 'San Diego',
    state: 'California',
    stateCode: 'CA',
    latitude: 32.7157,
    longitude: -117.1611,
    population: 1386932,
    wildfireRisk: 60,
    floodRisk: 15,
    hurricaneRisk: 5,
    heatWaveRisk: 35,
    droughtRisk: 65,
    avgSunshineHours: 9.2,
    avgCloudCover: 22,
    avgTempHigh: 72,
    avgTempLow: 58,
    costOfLivingIndex: 160,
    airQualityIndex: 42
  },
  {
    name: 'Sacramento',
    state: 'California',
    stateCode: 'CA',
    latitude: 38.5816,
    longitude: -121.4944,
    population: 524943,
    wildfireRisk: 65,
    floodRisk: 30,
    hurricaneRisk: 5,
    heatWaveRisk: 65,
    droughtRisk: 68,
    avgSunshineHours: 8.6,
    avgCloudCover: 28,
    avgTempHigh: 75,
    avgTempLow: 50,
    costOfLivingIndex: 130,
    airQualityIndex: 55
  },

  // Southwest - High drought, heat, low humidity
  {
    name: 'Phoenix',
    state: 'Arizona',
    stateCode: 'AZ',
    latitude: 33.4484,
    longitude: -112.074,
    population: 1608139,
    wildfireRisk: 50,
    floodRisk: 15,
    hurricaneRisk: 5,
    heatWaveRisk: 90,
    droughtRisk: 75,
    avgSunshineHours: 10.5,
    avgCloudCover: 18,
    avgTempHigh: 87,
    avgTempLow: 63,
    costOfLivingIndex: 105,
    airQualityIndex: 58
  },
  {
    name: 'Tucson',
    state: 'Arizona',
    stateCode: 'AZ',
    latitude: 32.2226,
    longitude: -110.9747,
    population: 548073,
    wildfireRisk: 55,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 85,
    droughtRisk: 70,
    avgSunshineHours: 10.2,
    avgCloudCover: 20,
    avgTempHigh: 83,
    avgTempLow: 57,
    costOfLivingIndex: 95,
    airQualityIndex: 52
  },
  {
    name: 'Las Vegas',
    state: 'Nevada',
    stateCode: 'NV',
    latitude: 36.1699,
    longitude: -115.1398,
    population: 641903,
    wildfireRisk: 40,
    floodRisk: 10,
    hurricaneRisk: 5,
    heatWaveRisk: 95,
    droughtRisk: 80,
    avgSunshineHours: 10.8,
    avgCloudCover: 15,
    avgTempHigh: 81,
    avgTempLow: 57,
    costOfLivingIndex: 110,
    airQualityIndex: 60
  },
  {
    name: 'Albuquerque',
    state: 'New Mexico',
    stateCode: 'NM',
    latitude: 35.0844,
    longitude: -106.6504,
    population: 564559,
    wildfireRisk: 55,
    floodRisk: 15,
    hurricaneRisk: 5,
    heatWaveRisk: 60,
    droughtRisk: 68,
    avgSunshineHours: 9.8,
    avgCloudCover: 22,
    avgTempHigh: 71,
    avgTempLow: 43,
    costOfLivingIndex: 92,
    airQualityIndex: 48
  },

  // Mountain States - Lower climate risk, cold winters
  {
    name: 'Denver',
    state: 'Colorado',
    stateCode: 'CO',
    latitude: 39.7392,
    longitude: -104.9903,
    population: 715522,
    wildfireRisk: 45,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 30,
    droughtRisk: 50,
    avgSunshineHours: 8.5,
    avgCloudCover: 30,
    avgTempHigh: 64,
    avgTempLow: 37,
    costOfLivingIndex: 125,
    airQualityIndex: 42
  },
  {
    name: 'Boulder',
    state: 'Colorado',
    stateCode: 'CO',
    latitude: 40.015,
    longitude: -105.2705,
    population: 108090,
    wildfireRisk: 50,
    floodRisk: 25,
    hurricaneRisk: 5,
    heatWaveRisk: 25,
    droughtRisk: 48,
    avgSunshineHours: 8.3,
    avgCloudCover: 32,
    avgTempHigh: 62,
    avgTempLow: 36,
    costOfLivingIndex: 155,
    airQualityIndex: 38
  },
  {
    name: 'Salt Lake City',
    state: 'Utah',
    stateCode: 'UT',
    latitude: 40.7608,
    longitude: -111.891,
    population: 200567,
    wildfireRisk: 40,
    floodRisk: 18,
    hurricaneRisk: 5,
    heatWaveRisk: 35,
    droughtRisk: 55,
    avgSunshineHours: 8.2,
    avgCloudCover: 35,
    avgTempHigh: 63,
    avgTempLow: 38,
    costOfLivingIndex: 105,
    airQualityIndex: 50
  },
  {
    name: 'Boise',
    state: 'Idaho',
    stateCode: 'ID',
    latitude: 43.615,
    longitude: -116.2023,
    population: 235684,
    wildfireRisk: 48,
    floodRisk: 20,
    hurricaneRisk: 5,
    heatWaveRisk: 32,
    droughtRisk: 45,
    avgSunshineHours: 7.5,
    avgCloudCover: 40,
    avgTempHigh: 63,
    avgTempLow: 39,
    costOfLivingIndex: 108,
    airQualityIndex: 44
  },

  // Texas - High heat, drought, some hurricane risk
  {
    name: 'Austin',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 30.2672,
    longitude: -97.7431,
    population: 961855,
    wildfireRisk: 35,
    floodRisk: 40,
    hurricaneRisk: 25,
    heatWaveRisk: 75,
    droughtRisk: 60,
    avgSunshineHours: 7.8,
    avgCloudCover: 35,
    avgTempHigh: 81,
    avgTempLow: 61,
    costOfLivingIndex: 115,
    airQualityIndex: 48
  },
  {
    name: 'Dallas',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 32.7767,
    longitude: -96.797,
    population: 1304379,
    wildfireRisk: 30,
    floodRisk: 35,
    hurricaneRisk: 20,
    heatWaveRisk: 80,
    droughtRisk: 65,
    avgSunshineHours: 7.5,
    avgCloudCover: 38,
    avgTempHigh: 78,
    avgTempLow: 58,
    costOfLivingIndex: 105,
    airQualityIndex: 52
  },
  {
    name: 'Houston',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 29.7604,
    longitude: -95.3698,
    population: 2304580,
    wildfireRisk: 20,
    floodRisk: 70,
    hurricaneRisk: 75,
    heatWaveRisk: 70,
    droughtRisk: 45,
    avgSunshineHours: 6.8,
    avgCloudCover: 45,
    avgTempHigh: 80,
    avgTempLow: 63,
    costOfLivingIndex: 98,
    airQualityIndex: 55
  },
  {
    name: 'San Antonio',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 29.4241,
    longitude: -98.4936,
    population: 1547253,
    wildfireRisk: 32,
    floodRisk: 45,
    hurricaneRisk: 30,
    heatWaveRisk: 78,
    droughtRisk: 58,
    avgSunshineHours: 7.6,
    avgCloudCover: 36,
    avgTempHigh: 80,
    avgTempLow: 61,
    costOfLivingIndex: 92,
    airQualityIndex: 50
  },

  // Southeast - High hurricane, flood, heat
  {
    name: 'Miami',
    state: 'Florida',
    stateCode: 'FL',
    latitude: 25.7617,
    longitude: -80.1918,
    population: 467963,
    wildfireRisk: 15,
    floodRisk: 85,
    hurricaneRisk: 95,
    heatWaveRisk: 65,
    droughtRisk: 25,
    avgSunshineHours: 8.5,
    avgCloudCover: 30,
    avgTempHigh: 84,
    avgTempLow: 72,
    costOfLivingIndex: 125,
    airQualityIndex: 40
  },
  {
    name: 'Tampa',
    state: 'Florida',
    stateCode: 'FL',
    latitude: 27.9506,
    longitude: -82.4572,
    population: 399700,
    wildfireRisk: 18,
    floodRisk: 75,
    hurricaneRisk: 90,
    heatWaveRisk: 68,
    droughtRisk: 28,
    avgSunshineHours: 8.2,
    avgCloudCover: 32,
    avgTempHigh: 82,
    avgTempLow: 68,
    costOfLivingIndex: 102,
    airQualityIndex: 42
  },
  {
    name: 'Orlando',
    state: 'Florida',
    stateCode: 'FL',
    latitude: 28.5383,
    longitude: -81.3792,
    population: 307573,
    wildfireRisk: 20,
    floodRisk: 60,
    hurricaneRisk: 85,
    heatWaveRisk: 70,
    droughtRisk: 30,
    avgSunshineHours: 7.9,
    avgCloudCover: 34,
    avgTempHigh: 83,
    avgTempLow: 66,
    costOfLivingIndex: 100,
    airQualityIndex: 45
  },
  {
    name: 'Jacksonville',
    state: 'Florida',
    stateCode: 'FL',
    latitude: 30.3322,
    longitude: -81.6557,
    population: 949611,
    wildfireRisk: 22,
    floodRisk: 55,
    hurricaneRisk: 80,
    heatWaveRisk: 65,
    droughtRisk: 32,
    avgSunshineHours: 7.6,
    avgCloudCover: 36,
    avgTempHigh: 80,
    avgTempLow: 61,
    costOfLivingIndex: 95,
    airQualityIndex: 43
  },
  {
    name: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    latitude: 33.749,
    longitude: -84.388,
    population: 498715,
    wildfireRisk: 25,
    floodRisk: 40,
    hurricaneRisk: 35,
    heatWaveRisk: 60,
    droughtRisk: 45,
    avgSunshineHours: 7.2,
    avgCloudCover: 40,
    avgTempHigh: 72,
    avgTempLow: 54,
    costOfLivingIndex: 105,
    airQualityIndex: 50
  },
  {
    name: 'Charleston',
    state: 'South Carolina',
    stateCode: 'SC',
    latitude: 32.7765,
    longitude: -79.9311,
    population: 150227,
    wildfireRisk: 20,
    floodRisk: 70,
    hurricaneRisk: 85,
    heatWaveRisk: 58,
    droughtRisk: 35,
    avgSunshineHours: 7.8,
    avgCloudCover: 35,
    avgTempHigh: 77,
    avgTempLow: 60,
    costOfLivingIndex: 110,
    airQualityIndex: 42
  },
  {
    name: 'Charlotte',
    state: 'North Carolina',
    stateCode: 'NC',
    latitude: 35.2271,
    longitude: -80.8431,
    population: 874579,
    wildfireRisk: 22,
    floodRisk: 35,
    hurricaneRisk: 45,
    heatWaveRisk: 55,
    droughtRisk: 40,
    avgSunshineHours: 7.4,
    avgCloudCover: 38,
    avgTempHigh: 71,
    avgTempLow: 51,
    costOfLivingIndex: 100,
    airQualityIndex: 46
  },
  {
    name: 'Raleigh',
    state: 'North Carolina',
    stateCode: 'NC',
    latitude: 35.7796,
    longitude: -78.6382,
    population: 467665,
    wildfireRisk: 20,
    floodRisk: 30,
    hurricaneRisk: 50,
    heatWaveRisk: 52,
    droughtRisk: 38,
    avgSunshineHours: 7.3,
    avgCloudCover: 39,
    avgTempHigh: 70,
    avgTempLow: 50,
    costOfLivingIndex: 98,
    airQualityIndex: 44
  },
  {
    name: 'Nashville',
    state: 'Tennessee',
    stateCode: 'TN',
    latitude: 36.1627,
    longitude: -86.7816,
    population: 689447,
    wildfireRisk: 18,
    floodRisk: 45,
    hurricaneRisk: 15,
    heatWaveRisk: 58,
    droughtRisk: 42,
    avgSunshineHours: 6.9,
    avgCloudCover: 42,
    avgTempHigh: 70,
    avgTempLow: 50,
    costOfLivingIndex: 102,
    airQualityIndex: 48
  },

  // Midwest - Low climate risk, cold winters, cloudy
  {
    name: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    latitude: 41.8781,
    longitude: -87.6298,
    population: 2746388,
    wildfireRisk: 10,
    floodRisk: 35,
    hurricaneRisk: 5,
    heatWaveRisk: 45,
    droughtRisk: 30,
    avgSunshineHours: 6.2,
    avgCloudCover: 52,
    avgTempHigh: 59,
    avgTempLow: 43,
    costOfLivingIndex: 110,
    airQualityIndex: 48
  },
  {
    name: 'Minneapolis',
    state: 'Minnesota',
    stateCode: 'MN',
    latitude: 44.9778,
    longitude: -93.265,
    population: 429954,
    wildfireRisk: 12,
    floodRisk: 30,
    hurricaneRisk: 5,
    heatWaveRisk: 35,
    droughtRisk: 28,
    avgSunshineHours: 6.5,
    avgCloudCover: 50,
    avgTempHigh: 51,
    avgTempLow: 36,
    costOfLivingIndex: 105,
    airQualityIndex: 40
  },
  {
    name: 'Milwaukee',
    state: 'Wisconsin',
    stateCode: 'WI',
    latitude: 43.0389,
    longitude: -87.9065,
    population: 577222,
    wildfireRisk: 10,
    floodRisk: 28,
    hurricaneRisk: 5,
    heatWaveRisk: 38,
    droughtRisk: 25,
    avgSunshineHours: 6.3,
    avgCloudCover: 51,
    avgTempHigh: 54,
    avgTempLow: 39,
    costOfLivingIndex: 95,
    airQualityIndex: 42
  },
  {
    name: 'Madison',
    state: 'Wisconsin',
    stateCode: 'WI',
    latitude: 43.0731,
    longitude: -89.4012,
    population: 269840,
    wildfireRisk: 8,
    floodRisk: 25,
    hurricaneRisk: 5,
    heatWaveRisk: 35,
    droughtRisk: 22,
    avgSunshineHours: 6.4,
    avgCloudCover: 50,
    avgTempHigh: 53,
    avgTempLow: 37,
    costOfLivingIndex: 105,
    airQualityIndex: 38
  },
  {
    name: 'Detroit',
    state: 'Michigan',
    stateCode: 'MI',
    latitude: 42.3314,
    longitude: -83.0458,
    population: 639111,
    wildfireRisk: 8,
    floodRisk: 30,
    hurricaneRisk: 5,
    heatWaveRisk: 40,
    droughtRisk: 24,
    avgSunshineHours: 5.8,
    avgCloudCover: 55,
    avgTempHigh: 56,
    avgTempLow: 41,
    costOfLivingIndex: 85,
    airQualityIndex: 45
  },
  {
    name: 'Grand Rapids',
    state: 'Michigan',
    stateCode: 'MI',
    latitude: 42.9634,
    longitude: -85.6681,
    population: 198917,
    wildfireRisk: 7,
    floodRisk: 26,
    hurricaneRisk: 5,
    heatWaveRisk: 36,
    droughtRisk: 20,
    avgSunshineHours: 5.9,
    avgCloudCover: 54,
    avgTempHigh: 54,
    avgTempLow: 39,
    costOfLivingIndex: 90,
    airQualityIndex: 42
  },
  {
    name: 'Columbus',
    state: 'Ohio',
    stateCode: 'OH',
    latitude: 39.9612,
    longitude: -82.9988,
    population: 905748,
    wildfireRisk: 10,
    floodRisk: 32,
    hurricaneRisk: 5,
    heatWaveRisk: 42,
    droughtRisk: 28,
    avgSunshineHours: 6.0,
    avgCloudCover: 53,
    avgTempHigh: 60,
    avgTempLow: 43,
    costOfLivingIndex: 92,
    airQualityIndex: 46
  },
  {
    name: 'Cleveland',
    state: 'Ohio',
    stateCode: 'OH',
    latitude: 41.4993,
    longitude: -81.6944,
    population: 372624,
    wildfireRisk: 8,
    floodRisk: 28,
    hurricaneRisk: 5,
    heatWaveRisk: 38,
    droughtRisk: 25,
    avgSunshineHours: 5.7,
    avgCloudCover: 56,
    avgTempHigh: 57,
    avgTempLow: 42,
    costOfLivingIndex: 88,
    airQualityIndex: 44
  },
  {
    name: 'Indianapolis',
    state: 'Indiana',
    stateCode: 'IN',
    latitude: 39.7684,
    longitude: -86.1581,
    population: 887642,
    wildfireRisk: 9,
    floodRisk: 33,
    hurricaneRisk: 5,
    heatWaveRisk: 44,
    droughtRisk: 30,
    avgSunshineHours: 6.1,
    avgCloudCover: 52,
    avgTempHigh: 60,
    avgTempLow: 43,
    costOfLivingIndex: 90,
    airQualityIndex: 47
  },
  {
    name: 'St. Louis',
    state: 'Missouri',
    stateCode: 'MO',
    latitude: 38.627,
    longitude: -90.1994,
    population: 301578,
    wildfireRisk: 12,
    floodRisk: 50,
    hurricaneRisk: 5,
    heatWaveRisk: 55,
    droughtRisk: 38,
    avgSunshineHours: 6.6,
    avgCloudCover: 48,
    avgTempHigh: 64,
    avgTempLow: 46,
    costOfLivingIndex: 88,
    airQualityIndex: 50
  },
  {
    name: 'Kansas City',
    state: 'Missouri',
    stateCode: 'MO',
    latitude: 39.0997,
    longitude: -94.5786,
    population: 508090,
    wildfireRisk: 15,
    floodRisk: 42,
    hurricaneRisk: 5,
    heatWaveRisk: 52,
    droughtRisk: 40,
    avgSunshineHours: 6.8,
    avgCloudCover: 46,
    avgTempHigh: 63,
    avgTempLow: 45,
    costOfLivingIndex: 92,
    airQualityIndex: 48
  },

  // Northeast - Low climate risk, cloudy, cold winters
  {
    name: 'New York',
    state: 'New York',
    stateCode: 'NY',
    latitude: 40.7128,
    longitude: -74.006,
    population: 8336817,
    wildfireRisk: 8,
    floodRisk: 45,
    hurricaneRisk: 50,
    heatWaveRisk: 45,
    droughtRisk: 22,
    avgSunshineHours: 6.5,
    avgCloudCover: 48,
    avgTempHigh: 62,
    avgTempLow: 48,
    costOfLivingIndex: 180,
    airQualityIndex: 52
  },
  {
    name: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    latitude: 42.3601,
    longitude: -71.0589,
    population: 675647,
    wildfireRisk: 7,
    floodRisk: 40,
    hurricaneRisk: 45,
    heatWaveRisk: 40,
    droughtRisk: 20,
    avgSunshineHours: 6.3,
    avgCloudCover: 50,
    avgTempHigh: 59,
    avgTempLow: 45,
    costOfLivingIndex: 155,
    airQualityIndex: 46
  },
  {
    name: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    latitude: 39.9526,
    longitude: -75.1652,
    population: 1603797,
    wildfireRisk: 10,
    floodRisk: 38,
    hurricaneRisk: 40,
    heatWaveRisk: 48,
    droughtRisk: 25,
    avgSunshineHours: 6.4,
    avgCloudCover: 49,
    avgTempHigh: 63,
    avgTempLow: 47,
    costOfLivingIndex: 108,
    airQualityIndex: 50
  },
  {
    name: 'Pittsburgh',
    state: 'Pennsylvania',
    stateCode: 'PA',
    latitude: 40.4406,
    longitude: -79.9959,
    population: 302971,
    wildfireRisk: 9,
    floodRisk: 32,
    hurricaneRisk: 10,
    heatWaveRisk: 42,
    droughtRisk: 23,
    avgSunshineHours: 5.6,
    avgCloudCover: 57,
    avgTempHigh: 60,
    avgTempLow: 43,
    costOfLivingIndex: 95,
    airQualityIndex: 48
  },
  {
    name: 'Baltimore',
    state: 'Maryland',
    stateCode: 'MD',
    latitude: 39.2904,
    longitude: -76.6122,
    population: 585708,
    wildfireRisk: 11,
    floodRisk: 40,
    hurricaneRisk: 42,
    heatWaveRisk: 50,
    droughtRisk: 26,
    avgSunshineHours: 6.5,
    avgCloudCover: 48,
    avgTempHigh: 64,
    avgTempLow: 47,
    costOfLivingIndex: 98,
    airQualityIndex: 49
  },
  {
    name: 'Washington',
    state: 'District of Columbia',
    stateCode: 'DC',
    latitude: 38.9072,
    longitude: -77.0369,
    population: 689545,
    wildfireRisk: 12,
    floodRisk: 42,
    hurricaneRisk: 40,
    heatWaveRisk: 52,
    droughtRisk: 28,
    avgSunshineHours: 6.6,
    avgCloudCover: 47,
    avgTempHigh: 65,
    avgTempLow: 48,
    costOfLivingIndex: 145,
    airQualityIndex: 48
  },
  {
    name: 'Buffalo',
    state: 'New York',
    stateCode: 'NY',
    latitude: 42.8864,
    longitude: -78.8784,
    population: 278349,
    wildfireRisk: 6,
    floodRisk: 28,
    hurricaneRisk: 12,
    heatWaveRisk: 32,
    droughtRisk: 18,
    avgSunshineHours: 5.5,
    avgCloudCover: 58,
    avgTempHigh: 55,
    avgTempLow: 40,
    costOfLivingIndex: 85,
    airQualityIndex: 42
  },
  {
    name: 'Providence',
    state: 'Rhode Island',
    stateCode: 'RI',
    latitude: 41.824,
    longitude: -71.4128,
    population: 190934,
    wildfireRisk: 8,
    floodRisk: 38,
    hurricaneRisk: 48,
    heatWaveRisk: 38,
    droughtRisk: 22,
    avgSunshineHours: 6.2,
    avgCloudCover: 51,
    avgTempHigh: 60,
    avgTempLow: 44,
    costOfLivingIndex: 112,
    airQualityIndex: 44
  },
  {
    name: 'Portland',
    state: 'Maine',
    stateCode: 'ME',
    latitude: 43.6591,
    longitude: -70.2568,
    population: 68408,
    wildfireRisk: 10,
    floodRisk: 30,
    hurricaneRisk: 35,
    heatWaveRisk: 28,
    droughtRisk: 20,
    avgSunshineHours: 6.0,
    avgCloudCover: 52,
    avgTempHigh: 54,
    avgTempLow: 39,
    costOfLivingIndex: 118,
    airQualityIndex: 38
  },
  {
    name: 'Burlington',
    state: 'Vermont',
    stateCode: 'VT',
    latitude: 44.4759,
    longitude: -73.2121,
    population: 44743,
    wildfireRisk: 8,
    floodRisk: 32,
    hurricaneRisk: 15,
    heatWaveRisk: 25,
    droughtRisk: 18,
    avgSunshineHours: 5.8,
    avgCloudCover: 54,
    avgTempHigh: 52,
    avgTempLow: 37,
    costOfLivingIndex: 120,
    airQualityIndex: 35
  },

  // Additional cities
  {
    name: 'Omaha',
    state: 'Nebraska',
    stateCode: 'NE',
    latitude: 41.2565,
    longitude: -95.9345,
    population: 486051,
    wildfireRisk: 18,
    floodRisk: 48,
    hurricaneRisk: 5,
    heatWaveRisk: 50,
    droughtRisk: 45,
    avgSunshineHours: 6.9,
    avgCloudCover: 45,
    avgTempHigh: 61,
    avgTempLow: 41,
    costOfLivingIndex: 88,
    airQualityIndex: 45
  },
  {
    name: 'Oklahoma City',
    state: 'Oklahoma',
    stateCode: 'OK',
    latitude: 35.4676,
    longitude: -97.5164,
    population: 681054,
    wildfireRisk: 38,
    floodRisk: 42,
    hurricaneRisk: 15,
    heatWaveRisk: 72,
    droughtRisk: 62,
    avgSunshineHours: 7.4,
    avgCloudCover: 40,
    avgTempHigh: 71,
    avgTempLow: 50,
    costOfLivingIndex: 85,
    airQualityIndex: 48
  },
  {
    name: 'Tulsa',
    state: 'Oklahoma',
    stateCode: 'OK',
    latitude: 36.154,
    longitude: -95.9928,
    population: 413066,
    wildfireRisk: 35,
    floodRisk: 40,
    hurricaneRisk: 12,
    heatWaveRisk: 70,
    droughtRisk: 58,
    avgSunshineHours: 7.2,
    avgCloudCover: 42,
    avgTempHigh: 70,
    avgTempLow: 49,
    costOfLivingIndex: 82,
    airQualityIndex: 46
  },
  {
    name: 'Louisville',
    state: 'Kentucky',
    stateCode: 'KY',
    latitude: 38.2527,
    longitude: -85.7585,
    population: 633045,
    wildfireRisk: 14,
    floodRisk: 48,
    hurricaneRisk: 10,
    heatWaveRisk: 54,
    droughtRisk: 35,
    avgSunshineHours: 6.3,
    avgCloudCover: 50,
    avgTempHigh: 64,
    avgTempLow: 46,
    costOfLivingIndex: 90,
    airQualityIndex: 48
  },
  {
    name: 'Memphis',
    state: 'Tennessee',
    stateCode: 'TN',
    latitude: 35.1495,
    longitude: -90.049,
    population: 633104,
    wildfireRisk: 16,
    floodRisk: 62,
    hurricaneRisk: 18,
    heatWaveRisk: 68,
    droughtRisk: 45,
    avgSunshineHours: 7.0,
    avgCloudCover: 43,
    avgTempHigh: 71,
    avgTempLow: 52,
    costOfLivingIndex: 85,
    airQualityIndex: 52
  },
  {
    name: 'Birmingham',
    state: 'Alabama',
    stateCode: 'AL',
    latitude: 33.5207,
    longitude: -86.8025,
    population: 200733,
    wildfireRisk: 20,
    floodRisk: 38,
    hurricaneRisk: 28,
    heatWaveRisk: 62,
    droughtRisk: 42,
    avgSunshineHours: 7.1,
    avgCloudCover: 42,
    avgTempHigh: 71,
    avgTempLow: 52,
    costOfLivingIndex: 82,
    airQualityIndex: 50
  },
  {
    name: 'New Orleans',
    state: 'Louisiana',
    stateCode: 'LA',
    latitude: 29.9511,
    longitude: -90.0715,
    population: 383997,
    wildfireRisk: 14,
    floodRisk: 90,
    hurricaneRisk: 95,
    heatWaveRisk: 72,
    droughtRisk: 32,
    avgSunshineHours: 7.2,
    avgCloudCover: 41,
    avgTempHigh: 78,
    avgTempLow: 62,
    costOfLivingIndex: 92,
    airQualityIndex: 54
  },
  {
    name: 'Baton Rouge',
    state: 'Louisiana',
    stateCode: 'LA',
    latitude: 30.4515,
    longitude: -91.1871,
    population: 227470,
    wildfireRisk: 16,
    floodRisk: 75,
    hurricaneRisk: 85,
    heatWaveRisk: 70,
    droughtRisk: 35,
    avgSunshineHours: 7.0,
    avgCloudCover: 43,
    avgTempHigh: 78,
    avgTempLow: 60,
    costOfLivingIndex: 88,
    airQualityIndex: 52
  },
  {
    name: 'Little Rock',
    state: 'Arkansas',
    stateCode: 'AR',
    latitude: 34.7465,
    longitude: -92.2896,
    population: 202591,
    wildfireRisk: 22,
    floodRisk: 52,
    hurricaneRisk: 15,
    heatWaveRisk: 66,
    droughtRisk: 48,
    avgSunshineHours: 6.8,
    avgCloudCover: 44,
    avgTempHigh: 70,
    avgTempLow: 51,
    costOfLivingIndex: 82,
    airQualityIndex: 48
  },
  {
    name: 'Des Moines',
    state: 'Iowa',
    stateCode: 'IA',
    latitude: 41.5868,
    longitude: -93.625,
    population: 214133,
    wildfireRisk: 12,
    floodRisk: 45,
    hurricaneRisk: 5,
    heatWaveRisk: 48,
    droughtRisk: 38,
    avgSunshineHours: 6.5,
    avgCloudCover: 49,
    avgTempHigh: 58,
    avgTempLow: 40,
    costOfLivingIndex: 90,
    airQualityIndex: 44
  },
  {
    name: 'Wichita',
    state: 'Kansas',
    stateCode: 'KS',
    latitude: 37.6872,
    longitude: -97.3301,
    population: 397532,
    wildfireRisk: 25,
    floodRisk: 38,
    hurricaneRisk: 5,
    heatWaveRisk: 64,
    droughtRisk: 55,
    avgSunshineHours: 7.3,
    avgCloudCover: 41,
    avgTempHigh: 66,
    avgTempLow: 45,
    costOfLivingIndex: 80,
    airQualityIndex: 46
  },
  {
    name: 'Sioux Falls',
    state: 'South Dakota',
    stateCode: 'SD',
    latitude: 43.5446,
    longitude: -96.7311,
    population: 192517,
    wildfireRisk: 15,
    floodRisk: 35,
    hurricaneRisk: 5,
    heatWaveRisk: 42,
    droughtRisk: 40,
    avgSunshineHours: 6.8,
    avgCloudCover: 47,
    avgTempHigh: 54,
    avgTempLow: 34,
    costOfLivingIndex: 88,
    airQualityIndex: 40
  },
  {
    name: 'Fargo',
    state: 'North Dakota',
    stateCode: 'ND',
    latitude: 46.8772,
    longitude: -96.7898,
    population: 125990,
    wildfireRisk: 14,
    floodRisk: 55,
    hurricaneRisk: 5,
    heatWaveRisk: 38,
    droughtRisk: 35,
    avgSunshineHours: 6.6,
    avgCloudCover: 50,
    avgTempHigh: 48,
    avgTempLow: 30,
    costOfLivingIndex: 92,
    airQualityIndex: 38
  },
  {
    name: 'Billings',
    state: 'Montana',
    stateCode: 'MT',
    latitude: 45.7833,
    longitude: -108.5007,
    population: 117116,
    wildfireRisk: 42,
    floodRisk: 22,
    hurricaneRisk: 5,
    heatWaveRisk: 32,
    droughtRisk: 48,
    avgSunshineHours: 7.2,
    avgCloudCover: 42,
    avgTempHigh: 56,
    avgTempLow: 35,
    costOfLivingIndex: 95,
    airQualityIndex: 42
  },
  {
    name: 'Missoula',
    state: 'Montana',
    stateCode: 'MT',
    latitude: 46.8721,
    longitude: -113.994,
    population: 73489,
    wildfireRisk: 58,
    floodRisk: 25,
    hurricaneRisk: 5,
    heatWaveRisk: 28,
    droughtRisk: 42,
    avgSunshineHours: 6.5,
    avgCloudCover: 48,
    avgTempHigh: 54,
    avgTempLow: 32,
    costOfLivingIndex: 105,
    airQualityIndex: 45
  },
  {
    name: 'Cheyenne',
    state: 'Wyoming',
    stateCode: 'WY',
    latitude: 41.14,
    longitude: -104.8202,
    population: 65132,
    wildfireRisk: 38,
    floodRisk: 18,
    hurricaneRisk: 5,
    heatWaveRisk: 28,
    droughtRisk: 45,
    avgSunshineHours: 7.8,
    avgCloudCover: 38,
    avgTempHigh: 56,
    avgTempLow: 32,
    costOfLivingIndex: 95,
    airQualityIndex: 38
  },
  {
    name: 'Anchorage',
    state: 'Alaska',
    stateCode: 'AK',
    latitude: 61.2181,
    longitude: -149.9003,
    population: 291247,
    wildfireRisk: 22,
    floodRisk: 18,
    hurricaneRisk: 5,
    heatWaveRisk: 8,
    droughtRisk: 12,
    avgSunshineHours: 4.2,
    avgCloudCover: 68,
    avgTempHigh: 42,
    avgTempLow: 30,
    costOfLivingIndex: 135,
    airQualityIndex: 28
  },
  {
    name: 'Honolulu',
    state: 'Hawaii',
    stateCode: 'HI',
    latitude: 21.3099,
    longitude: -157.8581,
    population: 350964,
    wildfireRisk: 28,
    floodRisk: 35,
    hurricaneRisk: 55,
    heatWaveRisk: 18,
    droughtRisk: 32,
    avgSunshineHours: 8.8,
    avgCloudCover: 28,
    avgTempHigh: 85,
    avgTempLow: 73,
    costOfLivingIndex: 195,
    airQualityIndex: 25
  },
  {
    name: 'Reno',
    state: 'Nevada',
    stateCode: 'NV',
    latitude: 39.5296,
    longitude: -119.8138,
    population: 264165,
    wildfireRisk: 62,
    floodRisk: 18,
    hurricaneRisk: 5,
    heatWaveRisk: 45,
    droughtRisk: 70,
    avgSunshineHours: 9.5,
    avgCloudCover: 22,
    avgTempHigh: 66,
    avgTempLow: 39,
    costOfLivingIndex: 115,
    airQualityIndex: 48
  },
  {
    name: 'Fort Worth',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 32.7555,
    longitude: -97.3308,
    population: 956709,
    wildfireRisk: 32,
    floodRisk: 38,
    hurricaneRisk: 18,
    heatWaveRisk: 78,
    droughtRisk: 64,
    avgSunshineHours: 7.4,
    avgCloudCover: 39,
    avgTempHigh: 77,
    avgTempLow: 57,
    costOfLivingIndex: 100,
    airQualityIndex: 50
  },
  {
    name: 'El Paso',
    state: 'Texas',
    stateCode: 'TX',
    latitude: 31.7619,
    longitude: -106.485,
    population: 678815,
    wildfireRisk: 45,
    floodRisk: 22,
    hurricaneRisk: 5,
    heatWaveRisk: 82,
    droughtRisk: 75,
    avgSunshineHours: 10.0,
    avgCloudCover: 20,
    avgTempHigh: 78,
    avgTempLow: 52,
    costOfLivingIndex: 85,
    airQualityIndex: 52
  },
  {
    name: 'Fresno',
    state: 'California',
    stateCode: 'CA',
    latitude: 36.7378,
    longitude: -119.7871,
    population: 542107,
    wildfireRisk: 72,
    floodRisk: 28,
    hurricaneRisk: 5,
    heatWaveRisk: 88,
    droughtRisk: 78,
    avgSunshineHours: 9.0,
    avgCloudCover: 24,
    avgTempHigh: 77,
    avgTempLow: 53,
    costOfLivingIndex: 105,
    airQualityIndex: 72
  },
  {
    name: 'Long Beach',
    state: 'California',
    stateCode: 'CA',
    latitude: 33.7701,
    longitude: -118.1937,
    population: 466742,
    wildfireRisk: 65,
    floodRisk: 22,
    hurricaneRisk: 5,
    heatWaveRisk: 48,
    droughtRisk: 68,
    avgSunshineHours: 8.8,
    avgCloudCover: 26,
    avgTempHigh: 73,
    avgTempLow: 58,
    costOfLivingIndex: 152,
    airQualityIndex: 60
  },
  {
    name: 'Oakland',
    state: 'California',
    stateCode: 'CA',
    latitude: 37.8044,
    longitude: -122.2712,
    population: 440646,
    wildfireRisk: 58,
    floodRisk: 28,
    hurricaneRisk: 5,
    heatWaveRisk: 25,
    droughtRisk: 62,
    avgSunshineHours: 8.0,
    avgCloudCover: 33,
    avgTempHigh: 67,
    avgTempLow: 52,
    costOfLivingIndex: 175,
    airQualityIndex: 48
  },
  {
    name: 'Mesa',
    state: 'Arizona',
    stateCode: 'AZ',
    latitude: 33.4152,
    longitude: -111.8315,
    population: 504258,
    wildfireRisk: 48,
    floodRisk: 18,
    hurricaneRisk: 5,
    heatWaveRisk: 92,
    droughtRisk: 76,
    avgSunshineHours: 10.6,
    avgCloudCover: 17,
    avgTempHigh: 88,
    avgTempLow: 64,
    costOfLivingIndex: 102,
    airQualityIndex: 56
  },
  {
    name: 'Virginia Beach',
    state: 'Virginia',
    stateCode: 'VA',
    latitude: 36.8529,
    longitude: -75.978,
    population: 459470,
    wildfireRisk: 15,
    floodRisk: 65,
    hurricaneRisk: 75,
    heatWaveRisk: 52,
    droughtRisk: 30,
    avgSunshineHours: 7.1,
    avgCloudCover: 42,
    avgTempHigh: 68,
    avgTempLow: 52,
    costOfLivingIndex: 105,
    airQualityIndex: 44
  },
  {
    name: 'Richmond',
    state: 'Virginia',
    stateCode: 'VA',
    latitude: 37.5407,
    longitude: -77.436,
    population: 226610,
    wildfireRisk: 16,
    floodRisk: 42,
    hurricaneRisk: 48,
    heatWaveRisk: 56,
    droughtRisk: 32,
    avgSunshineHours: 6.8,
    avgCloudCover: 44,
    avgTempHigh: 68,
    avgTempLow: 50,
    costOfLivingIndex: 100,
    airQualityIndex: 46
  },
  {
    name: 'Asheville',
    state: 'North Carolina',
    stateCode: 'NC',
    latitude: 35.5951,
    longitude: -82.5515,
    population: 94589,
    wildfireRisk: 28,
    floodRisk: 35,
    hurricaneRisk: 22,
    heatWaveRisk: 38,
    droughtRisk: 32,
    avgSunshineHours: 6.9,
    avgCloudCover: 45,
    avgTempHigh: 66,
    avgTempLow: 45,
    costOfLivingIndex: 108,
    airQualityIndex: 40
  },
  {
    name: 'Savannah',
    state: 'Georgia',
    stateCode: 'GA',
    latitude: 32.0809,
    longitude: -81.0912,
    population: 147780,
    wildfireRisk: 22,
    floodRisk: 58,
    hurricaneRisk: 78,
    heatWaveRisk: 68,
    droughtRisk: 38,
    avgSunshineHours: 7.6,
    avgCloudCover: 38,
    avgTempHigh: 77,
    avgTempLow: 59,
    costOfLivingIndex: 95,
    airQualityIndex: 45
  },
  {
    name: 'Cincinnati',
    state: 'Ohio',
    stateCode: 'OH',
    latitude: 39.1031,
    longitude: -84.512,
    population: 309317,
    wildfireRisk: 11,
    floodRisk: 38,
    hurricaneRisk: 8,
    heatWaveRisk: 46,
    droughtRisk: 30,
    avgSunshineHours: 6.1,
    avgCloudCover: 52,
    avgTempHigh: 61,
    avgTempLow: 44,
    costOfLivingIndex: 88,
    airQualityIndex: 48
  },
  {
    name: 'Ann Arbor',
    state: 'Michigan',
    stateCode: 'MI',
    latitude: 42.2808,
    longitude: -83.743,
    population: 123851,
    wildfireRisk: 7,
    floodRisk: 28,
    hurricaneRisk: 5,
    heatWaveRisk: 38,
    droughtRisk: 22,
    avgSunshineHours: 5.9,
    avgCloudCover: 54,
    avgTempHigh: 56,
    avgTempLow: 40,
    costOfLivingIndex: 115,
    airQualityIndex: 42
  },
  {
    name: 'Durham',
    state: 'North Carolina',
    stateCode: 'NC',
    latitude: 35.994,
    longitude: -78.8986,
    population: 283506,
    wildfireRisk: 18,
    floodRisk: 32,
    hurricaneRisk: 48,
    heatWaveRisk: 54,
    droughtRisk: 36,
    avgSunshineHours: 7.2,
    avgCloudCover: 40,
    avgTempHigh: 69,
    avgTempLow: 49,
    costOfLivingIndex: 102,
    airQualityIndex: 45
  }
];
