import {
  queryOptions,
  useQueryClient,
  useSuspenseQuery
} from '@tanstack/react-query';
import { Link } from '@tanstack/react-router';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
// Theme 6: canonical queryOptions lives here, exported from the feature barrel.
// Other features that need this data import these options , no re-declaration.
//
// Add FEATUREQueryKey to src/lib/query-keys.ts first:
//   export const FEATUREQueryKey = () => ['FEATURE'] as const;
import { FEATUREQueryKey } from '@/lib/query-keys';
import { deleteEntityMutation } from '../server/FEATURE.mutations';
import { getEntities } from '../server/FEATURE.queries';

export const entitiesQueryOptions = queryOptions({
  queryKey: FEATUREQueryKey(),
  queryFn: async () => {
    const result = await getEntities();
    if (!result.ok) throw new Error(result.message);
    return result.data;
  },
  staleTime: 30_000
});

export function FeaturePage() {
  const { data: entities } = useSuspenseQuery(entitiesQueryOptions);
  const queryClient = useQueryClient();
  const [actionError, setActionError] = useState<string | null>(null);
  // Two-step inline delete: confirmDeleteId holds the id pending confirmation.
  // biome's noConfirmAlert blocks window.confirm() , use this pattern instead.
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [deleting, setDeleting] = useState(false);

  const handleDelete = async (id: string) => {
    setActionError(null);
    setDeleting(true);
    const result = await deleteEntityMutation({ data: { id } });
    setDeleting(false);
    setConfirmDeleteId(null);
    if (!result.ok) {
      setActionError(result.message);
      return;
    }
    await queryClient.invalidateQueries({ queryKey: FEATUREQueryKey() });
  };

  return (
    <div className="max-w-2xl space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-bold">Entities</h1>
        </div>
        {/*
          Navigate to a dedicated create page instead of an inline form.
          IMPORTANT: always use to + params for parameterized routes.
          Template literals pass local tsc but fail CI , route types are
          generated by `bun run generate` which runs first in `make ci`.
        */}
        <Link
          className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          to="/FEATURE/new"
        >
          <Plus className="h-4 w-4" />
          New entity
        </Link>
      </div>

      {actionError && (
        <div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
          {actionError}
        </div>
      )}

      {entities.length === 0 ? (
        <p className="py-8 text-center text-sm text-muted-foreground">
          No entities yet.{' '}
          <Link className="text-primary hover:underline" to="/FEATURE/new">
            Add one.
          </Link>
        </p>
      ) : (
        <div className="space-y-2">
          {entities.map(entity => (
            <div
              className="flex items-center justify-between rounded-lg border px-4 py-3"
              key={entity.id}
            >
              <div className="space-y-1">
                <p className="text-sm font-medium">{entity.title}</p>
                <span className="rounded-full border px-2 py-0.5 text-xs text-muted-foreground">
                  {entity.status}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Link
                  className="rounded p-1 text-muted-foreground hover:bg-muted transition-colors"
                  params={{ entityId: entity.id }}
                  title="Edit entity"
                  to="/FEATURE/$entityId"
                >
                  <Pencil className="h-4 w-4" />
                </Link>
                {/*
                  Two-step delete , never use window.confirm() (biome noConfirmAlert).
                  First click sets confirmDeleteId; row shows inline Yes/Cancel.
                */}
                {confirmDeleteId === entity.id ? (
                  <span className="flex items-center gap-1 text-xs">
                    <button
                      className="rounded bg-destructive px-2 py-0.5 text-destructive-foreground disabled:opacity-50"
                      disabled={deleting}
                      onClick={() => void handleDelete(entity.id)}
                      type="button"
                    >
                      {deleting ? '…' : 'Yes'}
                    </button>
                    <button
                      className="rounded border px-2 py-0.5 hover:bg-muted"
                      disabled={deleting}
                      onClick={() => setConfirmDeleteId(null)}
                      type="button"
                    >
                      Cancel
                    </button>
                  </span>
                ) : (
                  <button
                    className="rounded p-1 text-muted-foreground transition-colors hover:text-destructive"
                    onClick={() => setConfirmDeleteId(entity.id)}
                    title="Delete entity"
                    type="button"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
